os: linux
dist: trusty
language: python
services: docker
sudo: false

env:
  global:
    - BASE=unifem/meshdb-desktop TAG=parallel

before_script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker pull $BASE

script:
  - 'docker build --tag unifem/overture-desktop:$TAG . && 
     docker push unifem/overture-desktop'
  - docker images
