sudo: required

services:
  - docker

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker build --tag unifem/overture-desktop . && docker push unifem/overture-desktop
  - docker images
