os: linux
dist: trusty
language: python
services: docker
sudo: false

env:
  global:
    - BASE=unifem/overture-desktop:base TAG=next

before_script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker pull $BASE

script:
  - - '[[ -n $(git log --since $(docker inspect $BASE | grep Created |
             perl -e "s/.+\"([\d-:T]+).+$/\$1/g" -p)) &&
       "$TRAVIS_EVENT_TYPE" == "push" && -n "$TRAVIS_COMMIT_RANGE" &&
        -z "$(git diff --name-only $TRAVIS_COMMIT_RANGE |
            grep -e Dockerfile -e .travis.yml -e image -e WELCOME)" ]] ||
    (docker build --tag unifem/overture-desktop:$TAG . &&
     docker push unifem/overture-desktop &&
     touch success)'
  - docker images
