os: linux
dist: trusty
language: python
services: docker
sudo: true

env:
  global:
    - BASE=unifem/overture-desktop:base TAG=petsc

before_script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker pull $BASE

script:
  # Build only if the commit range of a push contains Dockerfile or .travis.yml
  - '[[ -n $(git log --since $(docker inspect $BASE | grep Created |
                               perl -e "s/.+\"([\d-:T]+).+$/\$1/g" -p)) &&
        "$TRAVIS_EVENT_TYPE" == "push" && -n "$TRAVIS_COMMIT_RANGE" &&
        -z "$(git diff --name-only $TRAVIS_COMMIT_RANGE |
            grep -e Dockerfile -e .travis.yml -e image -e WELCOME)" ]] ||
    (docker build --tag unifem/overture-desktop:$TAG . &&
     docker push unifem/overture-desktop &&
     touch success)'
  - 'docker build --tag unifem/overture-desktop:$TAG . && 
     docker push unifem/overture-desktop'
  - docker images
